### ISSUE TITLE
Open ini file then click cancel causes crash exit-'MainWindow' object has no attribute 'machinePTE'

### ISSUE THREAD

**Issue by yeltrow** [jethornton/7i76e#12]
First -- Thank you so much for your efforts.  

I did a fresh install today using the wget method of the deb.
wget https://github.com/jethornton/7i76e/raw/master/7i76e_0.1.1_all.deb

I clicked Open an ini file.  Then thought "I don't have one" and clicked Cancel.  Program aborted with the message:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lib7i76e/loadini.py", line 30, in openini
    parent.machinePTE.appendPlainText('Open File Cancled')
AttributeError: 'MainWindow' object has no attribute 'machinePTE'
Aborted

**Comment by jethornton** [comment]
Thanks for the report, I'll fix that in a bit. I know exactly where that is.

JT
