### ISSUE TITLE
7i76 / 7i76e (possibly?) - Step & Dir joint/ axis as a spindle.

### ISSUE THREAD

**Issue by robertspark** [jethornton/7i76e#16]
Sorry John, odd ball comment / potential gap.

I've got a 7i92 + 7i76 configured for a lathe and I use one of the step and direct axis for the spindle (it's a servo).

Under PNCCONF I can set the axis as a spindle, but I noticed that under the 7i76 (and I suspect the 7i76e) I was not able to set the standard step and direct axis as a spindle.   (I just had a quick go at using your config tool instead of using PncConf  + I normally just resuse my config files so I was just having a go at using your configuration tools)   Please just close this if you don't see it as an issue as maybe I was just expecting the config tool to work similar to PncConf where you just select the relevant axis / major or minor and can also select a spindle from the same dropdown list.

**Comment by jethornton** [comment]
But I gave up working on my Mesa Configuration Tool and are removing them all.

**Comment by silopolis** [comment]
Le sam. 16 juil. 2022 à 22:45, jethornton ***@***.***> a
écrit :

> But I gave up working on my Mesa Configuration Tool and are removing them
> all.
>
What? You abandonned MesaCT project? 😱
