### ISSUE TITLE
Configurator fails to start

### ISSUE THREAD

**Issue by hoverdj** [jethornton/7i76e#17]
LinuxCNC 2.8.2.11.g6a3d0a434 on Debain 10.

Installed the configurator and tried running it from the Applications menu. Nothing. Tried running it from the terminal and got the following error. Not sure where to go from here.

:/usr/bin$ ./7i76e
Traceback (most recent call last):
  File "./7i76e", line 203, in <module>
    main()
  File "./7i76e", line 199, in main
    ex = MainWindow()
  File "./7i76e", line 71, in __init__
    buildcombos.build(self)
  File "/usr/lib/python3/dist-packages/lib7i76e/buildcombos.py", line 198, in build
    files = sorted([entry.path for entry in os.scandir(path) if entry.is_file()])
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/firmware'

**Comment by jethornton** [comment]
That's an odd error because no where do I use a path of /usr/bin/firmware.
I just pushed a new deb, install that one and see what you get.

**Comment by hoverdj** [comment]
Whatever you did (if anything) did the trick. Thanks much!
Darryl
