### ISSUE TITLE
Homing>Home field must be numeric

### ISSUE THREAD

**Issue by JetForMe** [jethornton/7i76e#3]
Apparently, the Homing>Home field must be numeric, according to this [reply](https://forum.linuxcnc.org/49-basic-configuration/36722-inifile-err-conversion-for-gantry-configuration-2-8-0-pre1-4740-g60416609a#135644) in the forum.

**Comment by jethornton** [comment]
Thanks for the bug report and yes they should be a number.

JT

**Comment by jethornton** [comment]
I'm not able to duplicate the error, can you give me more information as to what you did?

I grepped for the terms Xmin, YLeftMax and they are not in my tool anywhere so not sure how that got in the ini file. I also grepped LinuxCNC and none of those terms are there either.

JT

JT

**Comment by JetForMe** [comment]
Oh no, I entered those values, not knowing what `HOME` was supposed to be. I thought it was a description, not a location.

**Comment by jethornton** [comment]
I'll add a value check for that.

JT

**Comment by jethornton** [comment]
Added check for numerical values for home entries
