### ISSUE TITLE
Connector naming

### ISSUE THREAD

**Issue by Tinoky** [jethornton/7i76e#5]
Hello!
In "Inputs" tab, I suggest to replace frame names "Input 0 - 15" and "Input 16 - 31" by connector names "Inputs TB6" and "Inputs TB5" respectively as it is done in "Outputs" tab.

In "Pins" tab, two first connectors are actually named "TB1" and "TB2" whereas I think they should be "TB2" and "TB3".
I don't understand what happens with the third connector, but so far, I don't have any board connected.

**Comment by jethornton** [comment]
Fixed with commit 5c7957a
