### ISSUE TITLE
Physical pin not found

### ISSUE THREAD

**Issue by Tinoky** [jethornton/7i76e#7]
Hello dear friend!

In order to use analog spindle control, I had to comment out following lines in my main hal file:
# Spindle
#setp hm2_7i76e.0.pwmgen.00.output-type 0
#setp hm2_7i76e.0.pwmgen.00.scale [SPINDLE]MAX_RPM
#setp hm2_7i76e.0.pwmgen.pwm_frequency [SPINDLE]PWM_FREQUENCY

And then I had to add the following to my postgui.hal:

# Connect analog spindle speed output
net spindle-out spindle.0.speed-out-abs => hm2_[HOSTMOT2](BOARD).0.7i76.0.0.spinout

# Connect analog spindle controls for VFD driven by ENA/DIR wires
net spindle-on spindle.0.on => hm2_[HOSTMOT2](BOARD).0.7i76.0.0.spinena
net spindle-dir spindle.0.reverse => hm2_[HOSTMOT2](BOARD).0.7i76.0.0.spindir

setp hm2_[HOSTMOT2](BOARD).0.7i76.0.0.spinout-maxlim [SPINDLE]MAX_RPM
setp hm2_[HOSTMOT2](BOARD).0.7i76.0.0.spinout-minlim [SPINDLE]MIN_RPM
setp hm2_[HOSTMOT2](BOARD).0.7i76.0.0.spinout-scalemax [SPINDLE]SCALE

This seams to be working fine, but since my VFD is supposed to be driven by FWD/REV wires, I have also added two output pins "Spindle CW" and "Spindle CCW" to Output 6 and Output 7 respectively, and I think I should connect these pins something like follows:

# Connect analog spindle controls for VFD driven by FOR/REV wires
net spindle-fwd spindle.0.forward => hm2_[HOSTMOT2](BOARD).0.7i76.0.0.spinCW
net spindle-dir => hm2_[HOSTMOT2](BOARD).0.7i76.0.0.spinCCW

But since "spinCW" and "spinCCW" are purely hypothetical pin names, they are unknown, and I have no idea of good names. I wonder maybe they are missing?

Could you please help me?

**Comment by jethornton** [comment]
The spindle section is a copy of the 7i96 and is not correct. Please ask for help on the forum and post the solution here.

**Comment by jethornton** [comment]
This has been fixed
