### ISSUE TITLE
I get 404 error when attempting to download 7i76e config tool

### ISSUE THREAD

**Issue by kb8wmc** [jethornton/7i76e#9]
John, I was previously running your older 7i76e configuration tool but wanted to do upgrade to your latest work and using the .deb install...So I thought I would dump the older version to possibly avoid any conflicts and just download the new one...Then read over the instructions, I installed/upgraded dependencies, created an ".xsessionrc" file with the bash script in it, upgraded python3.5 to python-3.7.9 (which was almost a nightmare in itself), and then, attempted to download the configuration tool by clicking the "debian" highlight on the page, no joy...so I tried using the wget and got the exact same response, a "404" error..."This is not the page you are looking for."
  I am running Debian 9 (Stretch), 64 bit...I still have python3.5 installed on this computer as I have some other apps that may depend on it, don't know that for sure...But when I do a "python3 -V" it comes up as Python 3.7.9 as it should...I am wondering if I need to dump the old python 3.5?...I don't even know for sure that python has anything to do with the 404 error...Also I tried to upgrade pip as I thought that might have something to do with it, but I get a notice that pip points back to python 3.5...I am at a loss...Any input is appreciated...BTW, great job on the work you have put into development of these tools...
Thanks in advance
Mike Maxfield

**Comment by jethornton** [comment]
The correct link is https://github.com/jethornton/7i76e/raw/master/c7i76e_1.0.0_all.deb
I'll fix the documentation in the morning.

**Comment by kb8wmc** [comment]
John, thank you for fixing the link...I was able to download it without error...I managed to get pip upgraded to version 20.0.1 and python3.7, seems all well and is set with higher priority so it shows as "Python 3.7.9" when calling "python3 -V"... But when trying to run the gedbi-gtk installer to install the config tool it throws the error "Dependency is not satisfiable: python3 (>=3.6) ...
Any ideas?  I am running Debian 9, 64bit

**Comment by jethornton** [comment]
Not sure why you needed to upgrade pip as I don't use that any more.

I have at least one Debian 9 PC running, how did you upgrade to Python 3.7?

I don't support Debian 9 but I'll see if I can figure it out.

In the mean time try this deb I've removed the (>=3.6)
https://github.com/jethornton/7i76e/raw/master/c7i76e_1.0.1_p3.deb

**Comment by kb8wmc** [comment]
John, I downloaded link and clicked on file which opened it with gdebi...Attempted to install which brought up notice that I needed admin rights...Scratched my head, then entered my pw and got message that the pw was incorrect...
So I opened terminal and did a sudo gdebi-gtk, and it installed as it normally would...Then I attempted to open by typing in 7i76e, then I realized that I had to do c7i76e...I got this error message when trying c7i76e: 

File "/usr/bin/c7i76e", line 34
    self.setWindowTitle(f'7i76e Configuration Tool Version {self.version}')
                                                                         ^
SyntaxError: invalid syntax

The caret after Configuration was actually located beneath the single quote mark at the end...

Thanks John for all your efforts
Mike

**Comment by jethornton** [comment]
Did you get the 7i76e Configuration Tool menu in the CNC menu?

I'd bet it's using Python < 3.6 because that is a valid statement and I installed the deb on Debian 10 and tested. I need to put some code in to check the Python version at start up because that could be a confusing error message.

How did you install Python 3.7?

JT

**Comment by kb8wmc** [comment]
John, Sorry taking so long to get back to you, I had to take care of some things this afternoon...Yes to your first question, the configuration tool appears in CNC menu, although when clicking on it, it does not open the config tool...

Your second question, I downloaded Python 3.7.9 from the python website, followed all the instructions to compile it and it installed...

**Comment by kb8wmc** [comment]
John, I should have included the Python.org website that I got version 3.7 from...The only reason I installed the newer version was because the deb installer error indicated that I need a version greater that 3.6...
https://www.python.org/download/releases/

**Comment by jethornton** [comment]
I didn't see any install instructions at your link but did find some that said to do sudo make altinstall which will leave you with two versions of Python 3 installed. This has nothing to do with my configuration tool so I'm closing this issue.
